version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - echo Starting my build commands      
      - export BUCKET=cm-lambda-code-deploy
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --s3-prefix codepipeline --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml